version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  simple-upload-server:
    image: mayth/simple-upload-server
    ports:
      - "25478:25478"
    command:
      - -read_write_tokens
      - 856047d6d7c682bd0e7cbaa4e455af2a
      - -addr
      - simple-upload-server:25478
      - -document_root
      - /var/data
    volumes:
      - files:/var/data
volumes:
  cache:
  files:
